# This file was generated by GoReleaser. DO NOT EDIT.
cask "koikoi" do
  name "koikoi"
  desc "花札こいこいゲーム（CUI・任天堂ルール準拠）"
  homepage "https://github.com/ngs/go-koikoi"
  version "0.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "koikoi"

  on_macos do
    on_intel do
      url "https://github.com/ngs/go-koikoi/releases/download/v#{version}/go-koikoi_#{version}_darwin_amd64.zip"
      sha256 "1879675d8fa8ae26544dd8f71b49e49e3e9230feee5463567286c80c1f2df114"
    end
    on_arm do
      url "https://github.com/ngs/go-koikoi/releases/download/v#{version}/go-koikoi_#{version}_darwin_arm64.zip"
      sha256 "eb4dfebf328e332d0ca207b119a691ed4e4b0108ec7cfc9aeea66663c5421227"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ngs/go-koikoi/releases/download/v#{version}/go-koikoi_#{version}_linux_amd64.tar.gz"
      sha256 "267157091cdfd46ad360269eb2b5dc3c71af7c513ef4c046737e99c6fb946835"
    end
    on_arm do
      url "https://github.com/ngs/go-koikoi/releases/download/v#{version}/go-koikoi_#{version}_linux_arm64.tar.gz"
      sha256 "e78c2774bb419f1135ca70ab88d38446994ea24a83bceeb5a3b8dcf580146aee"
    end
  end

  # No zap stanza required
end
